name: manydepth
channels:
  - default
  - pytorch
  - conda-forge
dependencies:
  - opencv
  - matplotlib
  - numpy
  - pip
  - pip:
    - Pillow
    - tensorboardX
    - scikit-image
    - tqdm
    - ConfigArgParse
    - PyYAML
